widgets:
  -
    position: left
    type: profile
    author_title: Player & Contribution Dev
    location: Shangri-La City Center
    avatar: /images/avatars/DALLE-K4LM3D.png
    avatar_rounded: true
    gravatar: 
    # follow_link: https://github.com/K4LM3D
    social_links:
      Facebook:
        icon: fab fa-facebook
        url: https://facebook.com/k4lm3dgg
      Instagram:
        icon: fab fa-instagram
        url: https://www.instagram.com/k4lm3d
      TikTok:
        icon: fab fa-tiktok
        url: https://tiktok.com/@K4LM3D
      Kofi:
        icon: fab fa-ko-fi
        url: https://ko-fi.com/kalmedkaliber
  - 
    position: right
    type: toc
    index: true
  -
    position: right
    type: links
    links:
      Play CyberCode Online: https://cybercodeonline.com
  # -
  #   type: recent_posts
  #   position: right
  -
    type: categories
    position: right
  # -
  #   type: tags
  #   position: right
